wordpress:
  image:
    tag: 5.0.2 #invalid #break this app on purpose until a dedicated broken app is created
  wordpressPassword: foo
  mariadb:
    db:
      password: bar
    rootUser:
      password: baz
